### ISSUE TITLE
Error, Once the green bar finished and Minecraft started to launch, it crashed.

### ISSUE THREAD

**Issue by leifadev** [ZekerZhayard/OptiForge#1]
Once the green bar finished and Minecraft started to launch, it crashed.

I couldn't get the full log but here is the most I could get:
https://pastebin.com/CUphLebZ
I used both of your versions and they both didn't work (most likely same error)

Using this with OptiForge
I would really love to see this work!

Thanks!

**Comment by ZekerZhayard** [comment]
It works well for me with `Forge-1.15.2-31.1.17`, `OptiFine_1.15.2_HD_U_G1_pre9` and `OptiForge-1.1.0.`
Can you provide your modlist or `.minecraft/logs/debug.log`?

**Comment by leifadev** [comment]
https://pastebin.com/R3Pt3iSb
theres my debug log, trying your versions of optifine and forge, edit later

edit: i tried your versions and my game just crashes when i launch forge

**Comment by leifadev** [comment]
Ohhhh, I didn't catch that you had to drag the actual optifine jar in the mods folder as well. You should maybe clarify that in the wiki.

Thanks for this amazing mod!

**Comment by ZekerZhayard** [comment]
You provided the wrong log :(
Please install above mods, launch the game, crash, don't launch the game again, and paste the log.

I suspect that you didn't put OptiFine itself into the mods folder
