### ISSUE TITLE
求求了   更新1.18的opitforge吧     我等不及了   拜托

### ISSUE THREAD

**Issue by lzj12138LZJ** [ZekerZhayard/OptiForge#101]
求求了   更新1.18的opitforge吧     我等不及了   拜托

**Comment by ZekerZhayard** [comment]
optifine 1.18 自身已经兼容 forge 了，所以不需要这个了
而且 optiforge 受制于一个关键的 issue，https://github.com/cpw/modlauncher/issues/74，所以没法做
