### ISSUE TITLE
Crash w/ Forge Version 31.1.41

### ISSUE THREAD

**Issue by LonelyLeprechaun** [ZekerZhayard/OptiForge#13]
Here's the crash report:
[crash-2020-04-10_03.36.58-client.txt](https://github.com/ZekerZhayard/OptiForge/files/4460438/crash-2020-04-10_03.36.58-client.txt)

**Comment by ZekerZhayard** [comment]
check your mod list, maybe you installed duplicated optiforge mods.

**Comment by LonelyLeprechaun** [comment]
It looks like it wasn't working because I didn't have MixinBootstrap installed. Sorry!
