### ISSUE TITLE
Crash in game

### ISSUE THREAD

**Issue by jprocket45** [ZekerZhayard/OptiForge#14]
I have tried many different versions of forge 31.1.39 and above when loading it loads slow at the end then once in game you make it less than 5min with a crash this is with Optifine 1.15.2 pre13 without this the mods load fast and I have no issues.    https://pastebin.com/xgQ6sNA7  ,    also the newest version of forge will not even load this mod, keep up the good work and hope these is a fix for this!! here is one of many crash-report files i have when this mod is loaded.

**Comment by jprocket45** [comment]
after further looking into this I can't blame this mod for the crash that I know of unless the mod author sees otherwise the only true part that I have in there now is this doesn't not run on the newest forge it appears.

**Comment by ZekerZhayard** [comment]
This issue has been fixed in 0.1.9
