### ISSUE TITLE
Crash with Forge: 31.1.48 and Optifine G1 pre13

### ISSUE THREAD

**Issue by Suyiyi9547** [ZekerZhayard/OptiForge#18]
[authlib-injector.launch] [INFO] Version: 1.1.27-5ef5f8e

[authlib-injector.config] [INFO] API root: https://mcskin.littleservice.cn/api/yggdrasil/

[authlib-injector.config] [INFO] Prefetched metadata detected

2020-04-25 06:58:54,745 main WARN Advanced terminal features are not available in this environment

[32m[06:58:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Suyiyi, --version, HMCL 3.2.151, --gameDir, E:\1.15.2\.minecraft, --assetsDir, E:\1.15.2\.minecraft\assets, --assetIndex, 1.15, --uuid, c29f16b442bf4886b6fa7a3cc0e375e3, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.2.151, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.47, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200414.225201, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.48, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200414.225201]

[m[32m[06:58:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_251 by Oracle Corporation

[mMixinLoader 1.1 by IzzelAliz

Successfully add Mixin to classpath!

Successfully inject MixinLaunchPlugin!

[32m[06:58:55] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad

[m[32m[06:58:55] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: E:\1.15.2\.minecraft\mods\preview_OptiFine_1.15.2_HD_U_G1_pre13.jar

[m[32m[06:58:55] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust

[m[33m[06:58:55] [main/WARN] [MixinBootstrap Launch/]: MixinLaunchPlugin is already registered

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option launchTarget, but you asked for only one

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at joptsimple.OptionSet.valueOf(OptionSet.java:179)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.ArgumentHandler.lambda$processArguments$3(ArgumentHandler.java:66)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.ArgumentHandler.processArguments(ArgumentHandler.java:66)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.processArguments(TransformationServicesHandler.java:83)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:58)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)

[m[32m[06:58:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

[m

Exception in thread "main"

**Comment by ZekerZhayard** [comment]
不要同时安装 MixinLoader 和 MixinBootstrap，选一个就行
