### ISSUE TITLE
[Bug] Incompatibility with Journeymap

### ISSUE THREAD

**Issue by yezhiyi9670** [ZekerZhayard/OptiForge#19]
Note: I know it's known, but I still want to report it because it's now tracked nowhere.

## Description

Unrendered chunks can be found after traveling or teleporting for a distance, if Journeymap is also installed. Unlike the incompatibility between Optifine 1.12.2 and Journeymap, the unrendered chunks cannot be instantly rendered by triggering a block update inside it.

## Reliably Reproduce

1. Create a new Forge 1.15.2 game profile. Install MixinBootstrap, Journeymap, Optiforge and Optifine.
2. Create a superflat world using the default preset. After the creation, the chunks within your render distance will be rendered fine.
3. Travel or teleport to a place far away.  
❎ The far-away chunks are not rendered.
4. Try destroying or placing a block to trigger a block update in hidden chunks.  
❎ The hidden chunks are still not rendered.

## Relates to

This issue is a duplicate of #8. However, the author of #8 did not find out what caused the issue, and it is closed because it's "too random".

**Comment by ZekerZhayard** [comment]
I talked about this issue to the author of JournryMap last week. We all have no idea about this.  
This situation can be reproduced on 1.14.4, and I can be sure this is the problem of OptiFine.  
See sp614x/optifine#3731.  
If you know more infomation about this, please join our [Discord](https://discord.gg/kT2DQyW).

**Comment by yezhiyi9670** [comment]
This report is now a dupe of #8 and should be closed.
