### ISSUE TITLE
When I join a server the game disconnects "saving world" then game crashes

### ISSUE THREAD

**Issue by leifadev** [ZekerZhayard/OptiForge#2]
I just installed optiforge and mixin loader with optifine. I first joined a server and everything was going well the first time I joined. Then, the game crashed about 15 minutes into my playing. It said, "saving world" then the game crashes. I am not sure why this occurs. Can you help me out?

Heres my crash report:
https://pastebin.com/aDZ601HD

Edit: It seems also to crash when I drink or throw potions

**Comment by ZekerZhayard** [comment]
Fixed. Thanks for reporting!
