### ISSUE TITLE
[Bug] Emissive particles on item pickup

### ISSUE THREAD

**Issue by yezhiyi9670** [ZekerZhayard/OptiForge#20]
Note: I'm sure this is a bug of OptiForge. The bug cannot be reproduced anyway without it.

(But you know how buggy Optifine is without OptiForge)

Reproduce:

- Create a new world, set to night, peaceful, survival.
- Mine some dirt. Note that the destruction particles may become emissive for a few frames while picking up the dirt item.
- If this does not occur, restart the game and try again. Generally, it will occur in 3 tries.

**Comment by ZekerZhayard** [comment]
说实话，我没读懂你这个bug的具体表现，我也无法复现，你能录个视频嘛？

**Comment by yezhiyi9670** [comment]
I'll add screenshots first.

![image](https://user-images.githubusercontent.com/39194383/80974822-db3f2600-8e53-11ea-8a79-7c305ebd1654.png)

Does it look like this?

Note: I have a bad computer, and capturing may cause FPS lags which makes this issue unproduceable/invisible. I'll try to do so.

**Comment by ZekerZhayard** [comment]
可以在 Forge + OptiFine + 内置光影 下复现，不一定需要安装OptiForge

**Comment by yezhiyi9670** [comment]
I can reproduce it without shaders with OptiForge.

Btw, interested in fixing it?

**Comment by yezhiyi9670** [comment]
Interested in fixing it? (Sort of unplayable)

**Comment by ZekerZhayard** [comment]
has been fixed by optifine
