### ISSUE TITLE
Older versions support older Forger versions?

### ISSUE THREAD

**Issue by Unbuckle** [ZekerZhayard/OptiForge#21]
As I am playing HR New Beginnings, I cannot seem to get OptiForge and does OptiFine working. It is currently running on Forge Version 31.1.25 and for the current OptiForge version you need Forge 31.1.70 or higher. Are there any older OptiForge versions that support this Forge version?

**Comment by ZekerZhayard** [comment]
why not upgrade your forge version?

**Comment by Unbuckle** [comment]
because HR New Beginnings wouldnt work anymore then? I suppose? Im sorry if Im sounding dumb here but Im not most fluent with mods, so  could you elaborate?

**Comment by ZekerZhayard** [comment]
Which launcher are you using? Many launchers have the function that can change the forge version.

**Comment by Unbuckle** [comment]
The standard Minecraft launcher via the Twitch app

**Comment by ZekerZhayard** [comment]
I have never used Twitch Launcher.  
Are there any button for modifying forge version?

**Comment by Unbuckle** [comment]
Well yes I can create custom profiles with the required Forge version but then I cant choose the mod anymore. 
Which Launcer are you using, so I can swap to it if its possible there

**Comment by ZekerZhayard** [comment]
MultiMC can do that

**Comment by Unbuckle** [comment]
Well to begin with, MultiMC doesnt allow you to install Forge on Minecraft versions newer than 1.13 and HR new beginnings is at 1.15 already

**Comment by ZekerZhayard** [comment]
why?  
https://github.com/MultiMC/MultiMC5/blob/develop/changelog.md#multimc-0611  
Read the first line. MultiMC has supported forge 1.13+ since 0.6.11

**Comment by Unbuckle** [comment]
Ah interesting, because in the launcher it says "lets talk about forge" and brings you to this website saying they dont support it..

**Comment by Unbuckle** [comment]
This launcher is a bit complicated, how can I add the wanted Modpack there?
