### ISSUE TITLE
Crash On Startup - OptiForge-MC1.14.4-0.1.1

### ISSUE THREAD

**Issue by Birdman0071** [ZekerZhayard/OptiForge#22]
**Description**

Crash on startup while using only 3 mods + Optifine

-OptiForge-MC1.14.4-0.1.1.jar
-OptiFine_1.14.4_HD_U_F4
-MixinBootstrap-1.0.3.jar
-immersive-portals-0.14(for+mc+1.14+with+forge).jar

Forge version 1.14.4-forge-28.2.3

added logs only as there was no crash report 

[2020-05-24-1.log](https://github.com/ZekerZhayard/OptiForge/files/4675130/2020-05-24-1.log)

**Comment by ZekerZhayard** [comment]
related to https://github.com/qouteall/ImmersivePortalsModForForge/issues/104 and https://github.com/qouteall/ImmersivePortalsModForForge/issues/108 ,  
that's forge issue.

**Comment by Birdman0071** [comment]
Ah okay, thank you!
