### ISSUE TITLE
Optifine 1.15.2 HD U G1 pre26 Crash

### ISSUE THREAD

**Issue by HerrBeef** [ZekerZhayard/OptiForge#23]
Hi,

i've a problem with the new pre26 version of optifine and optiforge version 0.1.23.
it crashes very early. it works fine with pre24 so probably just an optifine update which broke it.

[2020-06-16-6.log](https://github.com/ZekerZhayard/OptiForge/files/4788212/2020-06-16-6.log)

**Comment by ZekerZhayard** [comment]
Can't reproduce.
Can you provide your mod list and `.minecraft/logs/debug.log`?

**Comment by sdas-tech** [comment]
Ive got the same issue.

Here's my mod list:
![image](https://user-images.githubusercontent.com/1049519/84852779-05b20f00-b0a1-11ea-8cc9-de73d3347868.png)

![image](https://user-images.githubusercontent.com/1049519/84852835-2c704580-b0a1-11ea-896f-9867e8e977f7.png)

Crashes with the following error:
The game crashed whilst rendering entity in world
Error: java.lang.IncompatibleClassChangeError: Method 'boolean net.minecraft.client.renderer.BlockModelRenderer.isSeparateAoLightValue()' must be Methodref constant


[debug.log](https://github.com/ZekerZhayard/OptiForge/files/4790261/debug.log)

**Comment by sdas-tech** [comment]
FYI I also get the same error using preview_OptiFine_1.15.2_HD_U_G1_pre23.

I cant find any other preview version of Optifine to test with.

**Comment by ZekerZhayard** [comment]
@sdas-tech ok, i reproduced your issue under java 9+
