### ISSUE TITLE
1.15.2 G1 pre30 + Optiforge latest crashes on startup

### ISSUE THREAD

**Issue by kouwei32** [ZekerZhayard/OptiForge#27]
**Environment:**
Windows 10
Forge 1.15.2-31.2.20
MixinBootstrap 1.0.3
Optiforge 0.1.24
Optifine G1 pre30

[debug.log](https://gist.github.com/kouwei32/6c903c01879730f3769ce0fd73e93bf1)

The error that appears to have caused this crash:
` org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$renderSky$0(Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;Lcom/mojang/blaze3d/matrix/MatrixStack;F)V in mixins.optiforge.json:net.minecraft.client.renderer.MixinWorldRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.optiforge.refmap.json`

**Comment by ZekerZhayard** [comment]
Fixed in 0.1.25

**Comment by kouwei32** [comment]
> Fixed in 0.1.25

Confirmed, works after updating to 0.1.25. Also that's some impressively fast patching.
