### ISSUE TITLE
1.15.2 Crash when loading world

### ISSUE THREAD

**Issue by ValkyrieSama** [ZekerZhayard/OptiForge#28]
Game is loading until the Main Menu, then crash whenever I try to open any save.

[crash-2020-06-22_03.36.50-client.txt](https://github.com/ZekerZhayard/OptiForge/files/4811854/crash-2020-06-22_03.36.50-client.txt)

**Comment by ZekerZhayard** [comment]
OptiFine released a second hotfix and fixed an issue which also fixed by OptiForge 0.1.25.  
These related codes have been removed in 0.1.26.
