### ISSUE TITLE
[1.15.2] Incompatibility with the Obfuscate mod

### ISSUE THREAD

**Issue by ocram9** [ZekerZhayard/OptiForge#29]
#### Description:

When launching the game it crashes while starting. According to the crash log it might be the Obfuscate mod (https://www.curseforge.com/minecraft/mc-mods/obfuscate) and removing it does fix it. However removing this mod fixes it too.

I have already reported this to Obfuscate but that mod isn't updated very frequently so maybe it's fixable on this end.

Crashlog: https://gist.github.com/ocram9/24dfb0e0805ceb236d6da9eb0ebce985

#### Versions:
- Optifine 1.15.2 pre-30 hotfix 2
- Minecraft 1.15.2
- Optiforge 0.1.26
- Forge 31.2.21
- Obfuscate 0.4.3

**Comment by ArMoReDfUrY** [comment]
i am getting the same crash (Bad Local Variable) but even though i have obfuscate i am not getting any mention of it in my crash logs.
MrCray does have a few incompatibilities in obfuscate that still need fixing... could be a while.

**Comment by ZekerZhayard** [comment]
https://www.curseforge.com/minecraft/mc-mods/obfuscate/issues/57  
I have been explained why Obfuscate mod won't cause crash with OptiFine but without OptiForge.  
There is nothing to do about OptiForge.  
One of feasible method is to make an another compatibility mod between Obfuscate and OptiForge if Obfuscate wasn't updated promptly,

**Comment by Tsoccerguy3** [comment]
issue is fixed here https://github.com/JacksonPlayz/Obfuscate/tree/mixin . You can compile yourself or wait for MrCrayfish to pull this fix

**Comment by ZekerZhayard** [comment]
It has been fixed by Obfuscate.
