### ISSUE TITLE
Crash when getting an effect

### ISSUE THREAD

**Issue by gekkone** [ZekerZhayard/OptiForge#3]
It is enough to get any effect and minecraft falls

> java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Float (java.lang.Integer and java.lang.Float are in module java.base of loader 'bootstrap')
> 	at net.minecraft.client.gui.IngameGui.redirect$zza000$redirect$renderPotionEffects$2(IngameGui.java:1662) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.gui.MixinIngameGui,pl:mixin:A}
> 	at net.minecraft.client.gui.IngameGui.func_194809_b(IngameGui.java:599) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.gui.MixinIngameGui,pl:mixin:A}
> 	at net.minecraftforge.client.gui.ForgeIngameGui.func_194809_b(ForgeIngameGui.java:239) ~[?:?] {re:classloading}
> 	at net.minecraftforge.client.gui.ForgeIngameGui.func_175180_a(ForgeIngameGui.java:188) ~[?:?] {re:classloading}
> 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:736) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-KiBClient%20(forge-31.1.19).jar:?] {re:classloading}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.19.jar:31.1] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

**Comment by ZekerZhayard** [comment]
Fixed.

**Comment by gekkone** [comment]
Thanks
