### ISSUE TITLE
1.15.2 G1 pre30 + Optiforge latest crashes on startup 

### ISSUE THREAD

**Issue by Mikegamer95** [ZekerZhayard/OptiForge#30]
[Info: 2020-06-24 20:55:14.1768521: GameCallbacks.cpp(158)] Game/game () Info 2020-06-24 13:55:14,174 main WARN Advanced terminal features are not available in this environment
[Info: 2020-06-24 20:55:14.3463298: GameCallbacks.cpp(158)] Game/game () Info [32m[13:55:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Mikegamer95, --version, 1.15.2-forge-31.2.23, --gameDir, C:\Users\Mikeg\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Mikeg\AppData\Roaming\.minecraft\assets, --assetIndex, 1.15, --uuid, 9cf9e52618d44cc9a32c88e6c43e43ee, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.23, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[Info: 2020-06-24 20:55:14.3517810: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[Info: 2020-06-24 20:55:14.6027278: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:14] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[Info: 2020-06-24 20:55:14.6063070: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:14] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\Mikeg\AppData\Roaming\.minecraft\mods\preview_OptiFine_1.15.2_HD_U_G1_pre30.jar
[Info: 2020-06-24 20:55:14.7852283: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:14] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[Info: 2020-06-24 20:55:14.8471913: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:14] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[Info: 2020-06-24 20:55:16.2415740: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Mikeg/AppData/Roaming/.minecraft/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=CLIENT
[Info: 2020-06-24 20:55:16.5220111: GameCallbacks.cpp(158)] Game/game () Info [mException in thread "main" [32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(Ljava/nio/file/Path;Lnet/minecraftforge/forgespi/locating/IModLocator;)V
[Info: 2020-06-24 20:55:16.5262325: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.zekerzhayard.optiforge.asm.fml.OptiForgeModLocator.scanMods(OptiForgeModLocator.java:24)
[Info: 2020-06-24 20:55:16.5270896: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer$$Lambda$225/271379554.apply(Unknown Source)
[Info: 2020-06-24 20:55:16.5274826: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[Info: 2020-06-24 20:55:16.5290918: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
[Info: 2020-06-24 20:55:16.5315305: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[Info: 2020-06-24 20:55:16.5319652: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[Info: 2020-06-24 20:55:16.5323532: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[Info: 2020-06-24 20:55:16.5336995: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[Info: 2020-06-24 20:55:16.5341567: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Info: 2020-06-24 20:55:16.5349475: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[Info: 2020-06-24 20:55:16.5355063: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:107)
[Info: 2020-06-24 20:55:16.5365039: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:213)
[Info: 2020-06-24 20:55:16.5370795: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[Info: 2020-06-24 20:55:16.5374536: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[Info: 2020-06-24 20:55:16.5377456: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[Info: 2020-06-24 20:55:16.5380670: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$192/379303133.apply(Unknown Source)
[Info: 2020-06-24 20:55:16.5383269: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
[Info: 2020-06-24 20:55:16.5385927: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
[Info: 2020-06-24 20:55:16.5388648: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[Info: 2020-06-24 20:55:16.5391174: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[Info: 2020-06-24 20:55:16.5393962: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[Info: 2020-06-24 20:55:16.5396685: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Info: 2020-06-24 20:55:16.5399238: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[Info: 2020-06-24 20:55:16.5401937: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[Info: 2020-06-24 20:55:16.5404566: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[Info: 2020-06-24 20:55:16.5407273: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[Info: 2020-06-24 20:55:16.5409848: GameCallbacks.cpp(158)] Game/game () Info [m[32m[13:55:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[Info: 2020-06-24 20:55:17.1718256: GameCallbacks.cpp(158)] Launcher/launcher (main) Info [m
[Info: 2020-06-24 20:55:17.1720193: GameCallbacks.cpp(158)] Launcher/monitor (Process Monitor) Fatal Process crashed with exit code 1
[Info: 2020-06-24 20:55:17.1933586: GameController.cpp(478)] Game closed with id 1
[Info: 2020-06-24 20:55:17.2011685: NetQueue.cpp(590)] NetQueue: Starting net action http://hopper.minecraft.net/crashes/submit_report/
[Info: 2020-06-24 20:55:17.6003894: NetQueue.cpp(469)] NetQueue: Primary ip: 35.168.97.233, Host: hopper.minecraft.net
[Info: 2020-06-24 20:55:17.6004990: NetQueue.cpp(536)] NetQueue: Action finished: http://hopper.minecraft.net/crashes/submit_report/
[Info: 2020-06-24 20:55:17.6007134: Process_Windows.cpp(283)] Finish any outstanding read/writes to the stdout stream
[Info: 2020-06-24 20:55:17.6174369: root_window_manager.cpp(83)] Main window has been opened: 0CFFF300
[Info: 2020-06-24 20:55:18.0240456: LauncherMain.cpp(84)] Initiated models
[Info: 2020-06-24 20:55:18.0242724: NetQueue.cpp(229)] NetQueue: Setting up.
[Info: 2020-06-24 20:55:18.0243300: LauncherMain.cpp(226)] Running launcher core (version 2.1.15167)
[Info: 2020-06-24 20:55:18.0260642: LauncherMain.cpp(93)] Initiated launcher controller
[Info: 2020-06-24 20:55:18.0264790: LauncherMain.cpp(241)] Initialization completed
[Info: 2020-06-24 20:55:18.0274635: LauncherMain.cpp(264)] Main process: false
[Info: 2020-06-24 20:55:18.0276890: LauncherMain.cpp(311)] workDir: ...\.minecraft
[Info: 2020-06-24 20:55:18.0277614: LauncherMain.cpp(319)] appDir: ...
[Info: 2020-06-24 20:55:18.0278177: NetQueue.cpp(229)] NetQueue: Setting up.
[Info: 2020-06-24 20:55:18.0278662: LauncherController.cpp(165)] Constructing launcher controller with workDir: ...\.minecraft, isActive: 0
[Info: 2020-06-24 20:55:18.0545045: LauncherAppRenderer.cpp(102)] Javascript bridge extended.
[Info: 2020-06-24 20:55:18.4392909: LauncherAppRenderer.cpp(246)] Creating renderer context
[Info: 2020-06-24 20:55:18.9217954: ControllerInterface.cpp(92)] Running method getStore
[Info: 2020-06-24 20:55:19.0093507: ControllerInterface.cpp(120)] Running async method checkForUpdates
[Info: 2020-06-24 20:55:19.0097173: NetQueue.cpp(590)] NetQueue: Starting net action https://launchermeta.mojang.com/v1/products/launcher/d03cf0cf95cce259fa9ea3ab54b65bd28bb0ae82/windows-x86.json
[Info: 2020-06-24 20:55:19.0668855: NetQueue.cpp(469)] NetQueue: Primary ip: 13.35.90.134, Host: launchermeta.mojang.com
[Info: 2020-06-24 20:55:19.0670005: NetQueue.cpp(536)] NetQueue: Action finished: https://launchermeta.mojang.com/v1/products/launcher/d03cf0cf95cce259fa9ea3ab54b65bd28bb0ae82/windows-x86.json
[Info: 2020-06-24 20:55:19.0673618: NetQueue.cpp(557)] NetQueue: Action finalized: https://launchermeta.mojang.com/v1/products/launcher/d03cf0cf95cce259fa9ea3ab54b65bd28bb0ae82/windows-x86.json
[Info: 2020-06-24 20:55:21.4232548: ControllerInterface.cpp(92)] Running method clearInstance

#

**Comment by lilblackpuppy** [comment]
Sams issue

**Comment by bendoerr** [comment]
Submitted this https://github.com/ZekerZhayard/OptiForge/pull/31

**Comment by LlubNek** [comment]
same issue here.
Tried forge 31.2.27 and 31.2.23
Works fine on 31.2.20
[2020-06-25-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/4834775/2020-06-25-1.log.gz)
[2020-06-25-2.log.gz](https://github.com/ZekerZhayard/OptiForge/files/4834776/2020-06-25-2.log.gz)

**Comment by bendoerr** [comment]
So forge clearly doesn't follow semver as they made a breaking API change in a bugfix rev.

**Comment by ZekerZhayard** [comment]
Fixed in https://github.com/ZekerZhayard/OptiForge/commit/ffc6c579449cfb986f4be587c5b9d4148e8e0bec
