### ISSUE TITLE
issues with Forge 31.2.27

### ISSUE THREAD

**Issue by Nanamiya738** [ZekerZhayard/OptiForge#32]
I use Forge(1.15) 31.0.27, and Optifine pre30, and the right version of OptiForge-0.1.27

but the screen become blank (white&purple Square)，that make me hard to see.

And it's normal with Forge 31.2.21, that's wired....

that's almost the same problem when I use Forge with wrong Optifine.  

so I think it must be a Compatibility issues or somewhat.

Is there any solution I can use for Now??

**Comment by ZekerZhayard** [comment]
It seems that it caused by https://github.com/sp614x/optifine/issues/4144, you downloaded the old pre30. You should redownload it at https://optifine.net/adloadx?f=preview_OptiFine_1.15.2_HD_U_G1_pre30.jar

**Comment by Nanamiya738** [comment]
Ok , thank you.

you are nice
