### ISSUE TITLE
everything is invisible 

### ISSUE THREAD

**Issue by tenkoshimura123** [ZekerZhayard/OptiForge#33]
I put on in internal shaders and this happened

without
![2020-07-09_16 14 01](https://user-images.githubusercontent.com/68080760/87086655-e28e0180-c1ff-11ea-812f-c6e9b3b02316.png)
![2020-07-09_16 16 10](https://user-images.githubusercontent.com/68080760/87086809-149f6380-c200-11ea-8eae-ba4691dee4d8.png)

with
![2020-07-09_16 14 34](https://user-images.githubusercontent.com/68080760/87086709-f5083b00-c1ff-11ea-9319-01c06c982d8c.png)
![2020-07-09_16 16 48](https://user-images.githubusercontent.com/68080760/87086960-47e1f280-c200-11ea-9f82-90e1090ae966.png)

**Comment by ZekerZhayard** [comment]
has been fixed since OptiFine 1.16.1 HD U G2 pre3.
