### ISSUE TITLE
crash while loading

### ISSUE THREAD

**Issue by Minecraft2p0** [ZekerZhayard/OptiForge#35]
Unfortunately, this mod is incompatible with Mr. Crayfish's Vehicle Mod. Can this be fixed?

**Comment by ZekerZhayard** [comment]
修了
![Y56I_8AQMX@8XO_P_YXJ~_C.png](https://i.loli.net/2020/08/11/4k86i5VWmbcnNOJ.png)

**Comment by Minecraft2p0** [comment]
I'll post the error log afterwards

**Comment by Minecraft2p0** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 10.08.20 20:04
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/entity/LivingRenderer.func_225623_a_(Lnet/minecraft/entity/LivingEntity;FFLcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;I)V @744: iload
  Reason:
    Type float (current frame, locals[21]) is not assignable to integer
  Current Frame:
    bci: @744
    flags: { }
    locals: { 'net/minecraft/client/renderer/entity/LivingRenderer', 'net/minecraft/entity/LivingEntity', float, float, 'com/mojang/blaze3d/matrix/MatrixStack', 'net/minecraft/client/renderer/IRenderTypeBuffer', integer, float, float, float, float, float, float, float, integer, 'net/minecraft/client/Minecraft', integer, integer, integer, 'net/minecraft/client/renderer/RenderType', 'com/mojang/blaze3d/vertex/IVertexBuilder', float, integer, 'net/minecraft/entity/LivingEntity' }
    stack: { 'net/minecraft/entity/LivingEntity', 'net/minecraft/client/renderer/entity/model/EntityModel', 'com/mojang/blaze3d/matrix/MatrixStack', 'com/mojang/blaze3d/vertex/IVertexBuilder', integer }
  Bytecode:
    0x0000000: b200 54b6 005a 9900 33b2 0054 1006 bd00
    0x0000010: 5c59 032b 5359 042a 5359 0525 b800 6253
    0x0000020: 5906 1904 5359 0719 0553 5908 1506 b800
    0x0000030: 6753 b800 6b99 0004 b1b2 006d 9900 082b
    0x0000040: 0cb5 0072 1904 b600 782a b400 322a 2b25
    0x0000050: b600 7cb5 0081 2ab4 0032 2bb6 0084 b500
    0x0000060: 87b2 008b b600 8e99 002e 2ab4 0032 2bb6
    0x0000070: 0084 9900 1f2b b600 92c6 0018 2bb6 0092
    0x0000080: b200 8b03 bd00 5cb8 0096 9900 0704 a700
    0x0000090: 0403 b500 872a b400 322b b600 99b5 009c
    0x00000a0: 252b b400 9f2b b400 a2b8 00a8 3807 252b
    0x00000b0: b400 ab2b b400 aeb8 00a8 3808 1708 1707
    0x00000c0: 6638 092a b400 32b4 0087 9900 6f2b b600
    0x00000d0: 92c1 006f 9900 652b b600 92c0 006f 3a0a
    0x00000e0: 2519 0ab4 009f 190a b400 a2b8 00a8 3807
    0x00000f0: 1708 1707 6638 0917 09b8 00b2 380b 170b
    0x0000100: 12b3 969c 0007 12b3 380b 170b 12b4 959b
    0x0000110: 0007 12b4 380b 1708 170b 6638 0717 0b17
    0x0000120: 0b6a 12b5 959e 000d 1707 170b 12b6 6a62
    0x0000130: 3807 1708 1707 6638 0925 2bb4 00b9 2bb4
    0x0000140: 00bc b800 bf38 0a2b b600 c3b2 00c9 a600
    0x0000150: 362b b600 cd3a 0b19 0bc6 002b 2bb2 00d0
    0x0000160: b600 d412 d566 380c 1904 190b b600 db74
    0x0000170: 8617 0c6a 8d0e 190b b600 de74 8617 0c6a
    0x0000180: 8db6 00e2 2a2b 25b6 00e5 380b 2a2b 1904
    0x0000190: 170b 1707 25b6 00e9 1904 12ea 12ea 0cb6
    0x00001a0: 00ee 2a2b 1904 25b6 00f2 1904 0e14 00f3
    0x00001b0: 0eb6 00e2 0b38 0c0b 380d 2b3a 172a 1917
    0x00001c0: b700 f89a 0040 2bb6 00fb 9900 3925 2bb4
    0x00001d0: 00fe 2bb4 0072 b800 bf38 0c2b b401 012b
    0x00001e0: b400 720c 2566 6a66 380d 2bb6 0099 9900
    0x00001f0: 0b17 0d13 0102 6a38 0d17 0c0c 959e 0006
    0x0000200: 0c38 0c2a b400 322b 170d 170c 25b6 0106
    0x0000210: 2ab4 0032 2b17 0d17 0c17 0b17 0917 0ab6
    0x0000220: 010a b801 0f99 002b 2a2b b501 112a 170d
    0x0000230: b501 132a 170c b501 152a 170b b501 172a
    0x0000240: 1709 b501 192a 170a b501 1b2a 25b5 011d
    0x0000250: b801 2236 0eb8 0128 3a0f 2a2b b601 2b36
    0x0000260: 1015 109a 0013 2b19 0fb4 012f b601 339a
    0x0000270: 0007 04a7 0004 0336 1119 0f2b b601 3736
    0x0000280: 122a 2b15 1015 1115 12b6 013b 3a13 1913
    0x0000290: c600 a219 0519 13b9 0141 0200 3a14 2a2b
    0x00002a0: 25b6 0144 3815 150e 9900 2d2b b401 489d
    0x00002b0: 000a 2bb4 014b 9e00 0c0c 0b0b 1301 4cb8
    0x00002c0: 0152 1715 0b95 9e00 0f17 1517 1517 1513
    0x00002d0: 0153 b801 522b 1715 b801 5736 162b 2ab4
    0x00002e0: 0032 1904 1914 1506 1515 170e 170d 170c
    0x00002f0: 170a 170b b801 5d9a 003b 2ab4 0032 1904
    0x0000300: 1914 1506 1516 0c0c 0c15 1199 0009 1301
    0x0000310: 5ea7 0004 0cb6 0162 2b2a b400 3219 0419
    0x0000320: 1415 0615 1517 0e17 0d17 0c17 0a17 0bb8
    0x0000330: 0166 2bb6 0169 9a00 3e2a b400 30b9 016d
    0x0000340: 0100 3a14 1914 b901 7201 0099 0029 1914
    0x0000350: b901 7601 00c0 0178 3a15 1915 1904 1905
    0x0000360: 1506 2b17 0d17 0c25 170b 1709 170a b601
    0x0000370: 7ca7 ffd3 b801 2299 000a 0b0b 0b0b b801
    0x0000380: 52b8 010f 9900 082a 01b5 0111 1904 b601
    0x0000390: 7f2a 2b24 2519 0419 0515 06b7 0182 b201
    0x00003a0: 85b6 005a 9900 30b2 0185 1006 bd00 5c59
    0x00003b0: 032b 5359 042a 5359 0525 b800 6253 5906
    0x00003c0: 1904 5359 0719 0553 5908 1506 b800 6753
    0x00003d0: b800 6b57 b1                           
  Stackmap Table:
    same_frame(@57)
    same_frame(@68)
    same_locals_1_stack_item_extended(@145,Object[#126])
    full_frame(@146,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer},{Object[#126],Integer})
    same_frame(@149)
    full_frame(@266,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Object[#111],Float},{})
    same_frame(@278)
    same_frame(@306)
    chop_frame(@313,2)
    append_frame(@388,Float)
    full_frame(@505,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Float,Float,Float,Float,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#111]},{})
    same_frame(@515)
    same_frame_extended(@592)
    full_frame(@630,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Object[#292],Integer,Top,Top,Top,Top,Top,Top,Object[#111]},{})
    same_locals_1_stack_item_frame(@631,Integer)
    full_frame(@697,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Object[#292],Integer,Integer,Integer,Object[#424],Object[#426],Float,Top,Object[#111]},{})
    same_frame(@706)
    same_frame(@725)
    full_frame(@788,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Object[#292],Integer,Integer,Integer,Object[#424],Object[#426],Float,Integer,Object[#111]},{Object[#126],Object[#116],Object[#426],Integer,Integer,Float,Float,Float})
    full_frame(@789,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Object[#292],Integer,Integer,Integer,Object[#424],Object[#426],Float,Integer,Object[#111]},{Object[#126],Object[#116],Object[#426],Integer,Integer,Float,Float,Float,Float})
    full_frame(@818,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Object[#292],Integer,Integer,Integer,Object[#424],Top,Top,Top,Object[#111]},{})
    full_frame(@836,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Object[#292],Integer,Integer,Integer,Object[#424],Object[#367],Top,Top,Object[#111]},{})
    full_frame(@884,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#317],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Object[#292],Integer,Integer,Integer,Object[#424],Top,Top,Top,Object[#111]},{})
    same_frame(@897)
    same_frame(@908)
    same_frame_extended(@980)

	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229097_a_(EntityRendererManager.java:103) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:quark:add-render}
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:215) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:quark:add-render}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:454) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$442/1758910325.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229097_a_(EntityRendererManager.java:103)
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:215)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:454)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$442/1758910325.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9222839512 bytes (8795 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.1_HD_U_G2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.1-0.1.9.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.1-0.1.9.jar optiforge TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 COMMON_SETUP}
		theoneprobe-1.16-3.0.1-beta.jar The One Probe {theoneprobe@1.16-3.0.1-beta COMMON_SETUP}
		forgeautofish-1.0.4-1.16.1.jar AutoFish for Forge {forgeautofish@1.0.4 COMMON_SETUP}
		MekanismAdditions-1.16.1-10.0.8.431.jar Mekanism: Additions {mekanismadditions@10.0.8 COMMON_SETUP}
		beenfo-1.16.1-forge32.0.38-1.1.4.jar Beenfo {beenfo@1.16.1-forge32.0.38-1.1.4 COMMON_SETUP}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 COMMON_SETUP}
		OptiForge-MC1.16.1-0.1.9.jar OptiForge {optiforge@0.1.9 COMMON_SETUP}
		movingelevators-1.2.17a-mc1.16.jar Moving Elevators {movingelevators@1.2.17a COMMON_SETUP}
		towers_of_the_wild-1.16.1-1.2.2.jar Towers Of the Wild {towers_of_the_wild@1.16.1-1.2.2 COMMON_SETUP}
		Mekanism-1.16.1-10.0.8.431.jar Mekanism {mekanism@10.0.8 COMMON_SETUP}
		torohealth-1.16.1-forge-2.jar ToroHealth {torohealth@NONE COMMON_SETUP}
		Xaeros_Minimap_20.18.0.1_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.18.0 COMMON_SETUP}
		XaerosWorldMap_1.8.1_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.8.1 COMMON_SETUP}
		AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 COMMON_SETUP}
		[1.16.1]+SecurityCraft+v1.8.19.1-beta2.jar SecurityCraft {securitycraft@v1.8.19.1-beta2 COMMON_SETUP}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 COMMON_SETUP}
		EndReborn+[0.7.5].jar End: Reborn {endreborn@0.7.5 COMMON_SETUP}
		DrawersTooltip-1.16.1-2.0.1.jar Drawers Tooltip {drawerstooltip@2.0.1 COMMON_SETUP}
		backpacked-1.5.1-1.16.1.jar Backpacked {backpacked@1.5.1 COMMON_SETUP}
		obfuscate-0.4.3-1.16.1.jar Obfuscate {obfuscate@0.4.3 COMMON_SETUP}
		vehicle-mod-0.45.0-1.16.1.jar MrCrayfish's Vehicle Mod {vehicle@0.45.0 COMMON_SETUP}
		DungeonCrawl-1.16.1-2.0.2.jar Dungeon Crawl {dungeoncrawl@2.0.2 COMMON_SETUP}
		worldedit-forge-mc1.16.1-7.2.0-beta-03.jar WorldEdit {worldedit@7.2.0-beta-03+94ce464 COMMON_SETUP}
		MekanismTools-1.16.1-10.0.8.431.jar Mekanism: Tools {mekanismtools@10.0.8 COMMON_SETUP}
		furniture-7.0.0-pre18-1.16.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre18 COMMON_SETUP}
		cc-tweaked-1.16.1-1.90.2.jar CC: Tweaked {computercraft@1.90.2 COMMON_SETUP}
		MekanismGenerators-1.16.1-10.0.8.431.jar Mekanism: Generators {mekanismgenerators@10.0.8 COMMON_SETUP}
		JustEnoughResources-1.16.1-0.11.1.93.jar Just Enough Resources {jeresources@0.11.1.93 COMMON_SETUP}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 COMMON_SETUP}
		Quark-r2.2-260.jar Quark {quark@r2.2-260 COMMON_SETUP}
		corpse-1.16.1-1.0.9.jar Corpse {corpse@1.16.1-1.0.9 COMMON_SETUP}
	Launched Version: 1.16.1-forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	OptiFine Version: OptiFine_1.16.1_HD_U_G2
	OptiFine Build: 20200802-005745
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by ZekerZhayard** [comment]
known issue: https://github.com/ZekerZhayard/OptiForge/issues/29
