### ISSUE TITLE
[1.16.1] Crash when a witch throws a potion.

### ISSUE THREAD

**Issue by Particle1904** [ZekerZhayard/OptiForge#37]
Im playing the Enigmatica6 0.2.10 with OptiFine 1.16.1 HD U G2 + OptiForge-MC1.16.1-0.1.9.
The Enigmatica discord moderator told me to report it to you guys so here it goes:

Enigmatica6 Modlist(I don't know if you need it): https://github.com/NillerMedDild/Enigmatica6/blob/master/MODLIST.md

Crash 1: https://pastebin.com/1zyV4xL8
Crash 2: https://pastebin.com/57ggi4sU

Thanks! :)

**Comment by Darkere** [comment]
We figured out that this is a bug in Apotheosis. That is originating from a bug in modlauncher. 
Apotheosis has fixed the issue.

**Comment by ZekerZhayard** [comment]
@Darkere any related links?

**Comment by Darkere** [comment]
Modlauncher issue: https://github.com/cpw/modlauncher/issues/57

Apotheosis Issue: https://github.com/Shadows-of-Fire/Apotheosis/issues/204

Forge Discord discussion: https://discordapp.com/channels/313125603924639766/733055378371117127/746137827577823372

**Comment by ZekerZhayard** [comment]
OK, waiting for modlauncher.
