### ISSUE TITLE
Not recongizing Optifine

### ISSUE THREAD

**Issue by AshOnDiscord** [ZekerZhayard/OptiForge#38]
I attempted to use optfine with forge on 1.15.2 so i downloaded the optiforge mod but optiforge keeps not recognizing
 my optifine jar(i am using the one from optifine client) I have also downloaded MixinBootstrap too.
The error image:
![nooptifine](https://user-images.githubusercontent.com/68016221/90919910-4b4acb00-e3b5-11ea-8488-ea7553d1dbd4.PNG)
Am i doing something wrong?
My mods folder:
![mods](https://user-images.githubusercontent.com/68016221/90920044-9b299200-e3b5-11ea-8b4e-c937eca0f5f5.PNG)

**Comment by ZekerZhayard** [comment]
where did you get this optifine jar?

**Comment by AshOnDiscord** [comment]
from the 1.15 optifine folder in the versions folder. Sorry for not replying earlier. I haven't checked up on GitHub in a while

**Comment by ZekerZhayard** [comment]
thats incorrect, you just need to put the optifine installer jar into the mods folder.

**Comment by AshOnDiscord** [comment]
oh ok thx
