### ISSUE TITLE
Crash when entering the block

### ISSUE THREAD

**Issue by gekkone** [ZekerZhayard/OptiForge#4]
For example, when /tp @s ~ ~-2 ~

>  java.lang.NoSuchMethodError: 'net.minecraft.util.math.BlockPos net.minecraft.util.math.BlockPos$Mutable.toImmutable()'
> 	at net.minecraft.client.renderer.OverlayRenderer.getOverlayBlock(OverlayRenderer.java:69) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:optiforge:OverlayRenderer,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinOverlayRenderer,pl:mixin:A}
> 	at net.minecraft.client.renderer.OverlayRenderer.redirect$zzl000$redirect$renderOverlays$0(OverlayRenderer.java:549) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:optiforge:OverlayRenderer,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinOverlayRenderer,pl:mixin:A}
> 	at net.minecraft.client.renderer.OverlayRenderer.func_228734_a_(OverlayRenderer.java:30) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:optiforge:OverlayRenderer,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinOverlayRenderer,pl:mixin:A}
> 	at net.minecraft.client.renderer.GameRenderer.renderHand(GameRenderer.java:604) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
> 	at net.minecraft.client.renderer.GameRenderer.func_228381_a_(GameRenderer.java:543) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
> 	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
> 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:688) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-KiBClient%20(forge-31.1.30).jar:?] {re:classloading}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.30.jar:31.1] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraft.client.renderer.OverlayRenderer.getOverlayBlock(OverlayRenderer.java:69)
> 	at net.minecraft.client.renderer.OverlayRenderer.redirect$zzl000$redirect$renderOverlays$0(OverlayRenderer.java:549)
> 	at net.minecraft.client.renderer.OverlayRenderer.func_228734_a_(OverlayRenderer.java:30)
> 	at net.minecraft.client.renderer.GameRenderer.renderHand(GameRenderer.java:604)
> 	at net.minecraft.client.renderer.GameRenderer.func_228381_a_(GameRenderer.java:543)
> 	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022)
> 
> -- Affected level --
> Stacktrace:
> 	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:573)
> 	at net.minecraft.client.main.Main.main(SourceFile:204)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by ZekerZhayard** [comment]
Fixed.
