### ISSUE TITLE
[Request]MineColonies + Optifine

### ISSUE THREAD

**Issue by TheRealM18** [ZekerZhayard/OptiForge#40]
Hello,  I know this is not a crash report, or it will not error out, but I would like the ability to get Optifine to work with the MineColonies NPCs.

What to expect...
NPC to be able to right click once they have a job.

What happens....
Unable to use the gui on rightclick even.

**Comment by ZekerZhayard** [comment]
https://github.com/sp614x/optifine/issues/4582

**Comment by ZekerZhayard** [comment]
It has been fixed by OptiFine: https://github.com/sp614x/optifine/issues/4582#issuecomment-697706669

Maybe backport this bug fix by OptiForge
