### ISSUE TITLE
1.16.2 Crash at Startup

### ISSUE THREAD

**Issue by xd4rkzghost01** [ZekerZhayard/OptiForge#42]
Hi there !! (sorry for my english i try my best)
I'm trying make a modded minecraft (without making a modpack [dunno how it works anyway]) and i encounter a crash right at startup with the error code "Exit : 0" Trying to figure out how it works but im lost it seems like optiforge work but cant run optifine??

There the Debug file dont know if it's usefull.
[debug.log](https://github.com/ZekerZhayard/OptiForge/files/5181780/debug.log)

But at least i know the latest.log file can help.
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/5181786/latest.log)

Also There are the Mods im using :
![Mods 1 16 2](https://user-images.githubusercontent.com/63568312/92363048-e1be0280-f0be-11ea-8725-a18218b8b605.png)

Can some1 help me or send me to the right place to find some help ?

**Edit :** Just trying to put more mode and Xaeros Minimap/World map and Apotheosis ran into the same error...

**Comment by ZekerZhayard** [comment]
modlauncher-7.0 broke Mixin, I can do nothing...
downgrade forge version to 33.0.37 should work.

**Comment by ZekerZhayard** [comment]
Also, this issue can be reproduced without OptiForge.

**Comment by xd4rkzghost01** [comment]
Well. Downgrade forge was corect. Thx for the help ^^'
