### ISSUE TITLE
[1.14.4 CRASH] Crashing upon attempting to load a world for no apparent reason.

### ISSUE THREAD

**Issue by ghost** [ZekerZhayard/OptiForge#45]
I've been recently experiencing a crash issue with OptiForge on 1.14.4, Forge version 28.2.23.
Where previously the mods have worked, they now for no apparent reason have started crashing for no reason.

Here is my crash log, titled "crash-2020-09-24_21.39.35-server" (why not client?? it's a singleplayer world!!):
[https://pastebin.com/FFR0Cbg9](url) Replaced with a Pastebin link because GitHub formatting was glitching out

Anyone got help on this? Would like to have shaders on 1.14 please, thanks.
_Thanks, --Catz._

PS: **This is not a MoreCrashData report.** If wanted, I can attempt to deliberately crash the game with the mod installed if this isn't enough information.

**Comment by ZekerZhayard** [comment]
It may be the issue of [Custom Quests](https://www.curseforge.com/minecraft/mc-mods/customquests)
