### ISSUE TITLE
Resource packs don't load on startup

### ISSUE THREAD

**Issue by goreae** [ZekerZhayard/OptiForge#5]
On MC 1.15.2, with optiforge 0.1.5, optifine G1_Pre10, and forge 31.1.30

I use the dokucraft resource pack. With optiforge and optifine enabled, upon startup Dokucraft is lot loaded. options .txt reads this: 

`resourcePacks:["vanilla","mod_resources","file/1.15-Dokucraft-TSC-Light","file/Dokucraft-Mod-Support"]`

I'm using two resource packs as you can see, dokucraft, and a dokucraft patch for appleskin. Both work perfectly fine. That line in options doesn't change at all, but when I close the game with Dokucraft enabled and restart, it restarts with it disabled. The only packs enabled are default and mod resources. I have to manually enable the packs every time I start up.

I know it's not optifine or forge that's the issue. Resource packs load just fine with just forge and work just fine on fabric with optifabric. So it must be an issue with optiforge. But it does say in the log `[m[33m[20:08:33] [Render thread/WARN] [ne.op.Config/]: [OptiFine] Unknown resource pack file: mod_resources` 
The full log: https://paste.ee/p/rDc0W

My theory is that optiforge changes the way resources are loaded to accomodate Optifine, but it fails to take into account the mod resources. It sees it listed in the options.txt, doesn't know what it's talking about, so errors out and fails to load any resource packs at all. Then after the resource pack loading is said and done, forge loads mod resources too late for the resource loader to do anything about it. Thus only default and mod-resources are loaded.

**Comment by ZekerZhayard** [comment]
Maybe fixed.
OptiFine calls Forge methods that should not be called in some places, I'm sure there are other places where I haven't found out yet.
