### ISSUE TITLE
1.16.3 server crash

### ISSUE THREAD

**Issue by mike1000195** [ZekerZhayard/OptiForge#50]
when optifine and optiforge for 1.16.3 works perfectly fine in client, but when i put them in the server mods to avoid a mod mismatch it just crashes the server almost instantly, it doesnt even get the chance to boot up. not sure if its incompatible with servers or not

**Comment by ZekerZhayard** [comment]
Both OptiFine and OptiForge are client side mods.

**Comment by mike1000195** [comment]
okay thanks. i looked in the description for anything saying that it wasn't a server sided mod before i posted an issue but i couldnt find anything. thanks again.

also, do you even need optiforge if you're using optifine as a standalone mod in the mods folder? what in general does optiforge even do?
