### ISSUE TITLE
OptiForge Black Screen on startup

### ISSUE THREAD

**Issue by ghost** [ZekerZhayard/OptiForge#54]
Optiforge version - Lastest 1.15.2
Forge version - 1.15.2-forge-31.2.0 (Reccomended)
When opening Forge with OptiForge installed the screen is black and client is stuck on the early loading progress.
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/5512732/latest.log)
No other mods in folder.
OS: MacOS - lastest version (idk if this matters)
Java 8

**Comment by Nick1st** [comment]
You need to have Optifine in your mods folder. You can get it from the original website: https://optifine.net/downloads
