### ISSUE TITLE
crash upon loading(yes another one...)

### ISSUE THREAD

**Issue by genericbrain** [ZekerZhayard/OptiForge#55]
hi good day, im sure there's a lot of dublicates or issues like this but in my defence i dont understand the logs, morecrash info is not updated to version1.16.1, and after a bit of reading none of the similar closed issues i've read ofer any solution nor do any other forum.
i've determined the problem is optiforge thru checking each mod individually. as im trying to fix some missing textures deleting a side this mod is not an option, i ask for help/counsil/solution (any respose iat all would exede expectations)
if it's worth mentioning the missing textures are the cables/conduits from MekanismV10
note : english is not my first lenguage so i apologise for any/all mistakes in the text.

optiforge version 1.16.1-0.1.10
optifine version 1.16.1._HD_U_G2
forge version 1.16.1-forge-32.0.108

[2020-11-22-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/5580646/2020-11-22-1.log.gz)

crash report does not show up

**Comment by Karlb2222** [comment]
I am having the same issue. I was attempting to fix missing textures with the mekanism mod.
It appears as though Optifine is only compatible up to forge-32.0.98 for 1.16.1 so I tried using optiforge to fix compatibility issues
optiforge: 1.16.1-0.1.11
optifine: 1.16.1 HD U G2
forge: 1.16.1-forge-32.0.108

When I try to launch the game with these I get a crash with the message 
java.lang.VerifyError: Bad local variable type
Exit Code: -1
 
Crash report here: https://pastebin.com/u5GkqD8N

**Comment by ZekerZhayard** [comment]
OptiFine itself is not compatible with Obfuscate
https://github.com/MrCrayfish/Obfuscate/issues/3

**Comment by Tsoccerguy3** [comment]
issue is fixed here https://github.com/JacksonPlayz/Obfuscate/tree/mixin . You can compile yourself or wait for MrCrayfish to pull this fix
