### ISSUE TITLE
[1.15.2] Version 0.1.31 crash on startup.

### ISSUE THREAD

**Issue by Nereithr** [ZekerZhayard/OptiForge#56]
0.1.31 crashes on startup with the latest OptiFine HD U G5 pre1 and MixinBootstrap 1.0.5. No other mods are installed. 0.1.30 works flawlessly. Attaching latest.log and debug.log.

[debug.log](https://github.com/ZekerZhayard/OptiForge/files/5603182/debug.log)
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/5603183/latest.log)

**Comment by ZekerZhayard** [comment]
Fixed in 1.15.2-0.1.32
