### ISSUE TITLE
Render Nameplate Crash

### ISSUE THREAD

**Issue by WenXin20** [ZekerZhayard/OptiForge#6]
`Minecraft v1.15.2`
`Forge v31.1.27`
`OptiFine vHD U G1 Pre 10`
`OptiForge v0.1.6`

The game crashes as soon as I try to load a world. No other mods or resourcepacks are installed.
[Crash Report](https://gist.github.com/WenXin20/396f4013b5b8570cc05dc02210c545bf)

**Comment by ZekerZhayard** [comment]
Please use Forge 31.1.30

**Comment by WenXin20** [comment]
That fixed it, thanks!
