### ISSUE TITLE
Latest version of optifine is getting called too old 

### ISSUE THREAD

**Issue by A-wolf** [ZekerZhayard/OptiForge#61]
![image](https://user-images.githubusercontent.com/33517791/103220519-bb97c900-4920-11eb-9348-9ad73c58b3c0.png)

I tested with both the latest full 1.16.4 G5 and 1.16.4 G6_pre and i am getting the same error telling me to install 1.16.1 G2_pre16 or newer

**Comment by ZekerZhayard** [comment]
you should use OptiForge for Minecraft 1.16.4, it seems you are using OptiForge for Minecraft 1.16.1
