### ISSUE TITLE
forge 35.1.28 incompatability

### ISSUE THREAD

**Issue by ghost** [ZekerZhayard/OptiForge#62]
Getting the following crash: https://pastebin.com/hFG3Rrqg

Update for Quark needs forge 35.1.28

Forge 35.1.28 and this mod seem incompatable (sorry to be the bearer of bad news)

The game crashes very fast (not your standard crash either....before it gets to a stage where a crash report is made, the log above is teh "latest")

The instance is being loaded from GD Launcher

**Comment by ghost** [comment]
With optiforge turned off and preview_OptiFine_1.16.4_HD_U_G6_pre7 in the mods folder the client loads fine
Does seem to be an optiforge issue rather than an optifine one

**Comment by ZekerZhayard** [comment]
Fixed in 1.16.4-0.4.4
