### ISSUE TITLE
Optiforge not recognizing newest version of optifine

### ISSUE THREAD

**Issue by kitkam** [ZekerZhayard/OptiForge#69]
I started up my minecraft and have reinstalled both forge and optifine twice, using both the newest versions that are buggy and the stable versions. I keep getting this pop up telling me that I don't have the right version of optifine installed. 
![image_2021-01-24_005338](https://user-images.githubusercontent.com/77915053/105624396-993d8200-5dde-11eb-9c5d-8c6806297ae5.png)

**Comment by ZekerZhayard** [comment]
OptiForge has not been released for 1.16.5
