### ISSUE TITLE
Doesn't OptiFine already support forge?

### ISSUE THREAD

**Issue by EnergixCoding** [ZekerZhayard/OptiForge#70]
I've been using optifine as a forge mod for a long time and its worked without this.

Are there some versions that dont support forge as im confused?

**Comment by jusitnboggs** [comment]
Yeah, Like what is this mod for?

**Comment by EnterFor** [comment]
I want to know, too..

**Comment by ZekerZhayard** [comment]
OptiForge is more useless for now, only when OptiFine can't keep up with Forge's progress, OptiForge is useful.

**Comment by EnergixCoding** [comment]
> OptiForge is more useless for now, only when OptiFine can't keep up with Forge's progress, OptiForge is useful.

Oh that makes sense, good to know.
