### ISSUE TITLE
Not Launching

### ISSUE THREAD

**Issue by yaNasTy** [ZekerZhayard/OptiForge#71]
Optiforge installer is not launching but the normal Opftine is so -rep

**Comment by ZekerZhayard** [comment]
please provide your logs (`.minecraft/logs/debug.log`)

**Comment by Sovthia** [comment]
[debug.log](https://github.com/ZekerZhayard/OptiForge/files/5993878/debug.log)

**Comment by ZekerZhayard** [comment]
> [debug.log](https://github.com/ZekerZhayard/OptiForge/files/5993878/debug.log)

@Sovthia 你的 OptiForge 版本太老了，更新到 1.16.4-0.4.6
