### ISSUE TITLE
says i have not put optifine in to mods folder? but i have?

### ISSUE THREAD

**Issue by firestorm2039** [ZekerZhayard/OptiForge#72]
i have forge 1.16.4
and just downloaded latest 1.16.4 version of this mod and get this error message
![Untitled](https://user-images.githubusercontent.com/75093996/109572779-b6ecbe00-7ae5-11eb-8837-3d726e9e7456.png)

**Comment by ZekerZhayard** [comment]
You need to put standard optifine jar into mods folder, DO NOT put the installed jar which in `.minecraft/versions`

**Comment by firestorm2039** [comment]
> You need to put standard optifine jar into mods folder, DO NOT put the installed jar which in `.minecraft/versions`

sorry for the late reply.
what do you mean? i downloaded it, then cut and paste it to mods folder (like i do with all mods). as seen in photo below
![Untitled](https://user-images.githubusercontent.com/75093996/110101623-b2512f80-7d9b-11eb-948a-a6b89ec90248.png)

**Comment by ZekerZhayard** [comment]
@firestorm2039 ah yeah, there is even no optifine jar in your mods folder, you should download it from https://www.optifine.net/downloads

**Comment by firestorm2039** [comment]
> @firestorm2039 ah yeah, there is even no optifine jar in your mods folder, you should download it from https://www.optifine.net/downloads

i have done that, now i get game crash error on start up (does not even load the game 1st)
i just installed OptiFine_1.16.4_HD_U_G7 to the mods folder
all other mods are the same as before 

i am also using forge-1.16.4-35.1.37-installer

![Untitled](https://user-images.githubusercontent.com/75093996/110112438-a9fff100-7da9-11eb-8675-9014dd5fa475.png)

**Comment by ZekerZhayard** [comment]
> > @firestorm2039 ah yeah, there is even no optifine jar in your mods folder, you should download it from https://www.optifine.net/downloads
> 
> i have done that, now i get game crash error on start up (does not even load the game 1st)
> i just installed OptiFine_1.16.4_HD_U_G7 to the mods folder
> all other mods are the same as before
> 
> i am also using forge-1.16.4-35.1.37-installer
> 
> ![Untitled](https://user-images.githubusercontent.com/75093996/110112438-a9fff100-7da9-11eb-8675-9014dd5fa475.png)

![Y56I 8AQMX@8XO%P(YXJ~}C](https://user-images.githubusercontent.com/41327811/110113297-e0f7f600-7ded-11eb-888e-8b854bc365aa.png)
please provide the crash logs. It's in `.minecraft/logs/debug.log` and `.minecraft/crash-reports`

**Comment by firestorm2039** [comment]
> > > @firestorm2039 ah yeah, there is even no optifine jar in your mods folder, you should download it from https://www.optifine.net/downloads
> > 
> > 
> > i have done that, now i get game crash error on start up (does not even load the game 1st)
> > i just installed OptiFine_1.16.4_HD_U_G7 to the mods folder
> > all other mods are the same as before
> > i am also using forge-1.16.4-35.1.37-installer
> > ![Untitled](https://user-images.githubusercontent.com/75093996/110112438-a9fff100-7da9-11eb-8675-9014dd5fa475.png)
> 
> ![Y56I 8AQMX@8XO%P(YXJ~}C](https://user-images.githubusercontent.com/41327811/110113297-e0f7f600-7ded-11eb-888e-8b854bc365aa.png)
> please provide the crash logs. It's in `.minecraft/logs/debug.log` and `.minecraft/crash-reports`

there is no crash report in the crash folder (not for today anyway) as it didnt crash in game, it crashed as soon as you hit play, so the report does not show up on there.
here is the debug file anyway
[debug.log](https://github.com/ZekerZhayard/OptiForge/files/6090726/debug.log)

**Comment by ZekerZhayard** [comment]
it looks like your Immersive Portal was too old, and not compatible with new OptiFine. There is a new Immersive Portal version available on CurseForge

**Comment by firestorm2039** [comment]
> it looks like your Immersive Portal was too old, and not compatible with new OptiFine. There is a new Immersive Portal version available on CurseForge

thank you, that seems to have worked, i always forget to update my mods lol
Thank you
