### ISSUE TITLE
Optiforge says Optifine is outdated when its not

### ISSUE THREAD

**Issue by carstorm** [ZekerZhayard/OptiForge#76]
![image](https://user-images.githubusercontent.com/7497589/113027696-ff80b100-914f-11eb-809b-14c17df0313d.png)

As the above shows optiforge is wanting a 1.16.4 version of optifine when I'm already on a newer 1.16.5 version. This is with optiforge 1.16.5-0.5.5 and the above shown optifine.

**Comment by ZekerZhayard** [comment]
Use OptiForge-MC1.16.4 for Minecraft 1.16.4 and OptiForge-MC-1.16.5 on Minecraft 1.16.5.
Both OptiForge and OptiFine are unable to cross versions.

**Comment by carstorm** [comment]
> Use OptiForge-MC1.16.4 for Minecraft 1.16.4 and OptiForge-MC-1.16.5 on Minecraft 1.16.5.
> Both OptiForge and OptiFine are unable to cross versions.

Opps found the problem. Curseforge didn't delete the old jar when updating meaning I had 2 version of optiforge installed. Sorry for bothering you. Manually deleted . 16.4 version and now it works as expected.
