### ISSUE TITLE
Geckolib3 with Optifine 1.16.5

### ISSUE THREAD

**Issue by MagicWubba** [ZekerZhayard/OptiForge#78]
It seems that Optifine 1.16.5 doesnt work with this mod dependency? 
Whenever i loaded either up without eachother it worked just fine no problems

**Comment by ZekerZhayard** [comment]
can you provide your logs?

**Comment by MagicWubba** [comment]
I managed to figure it out, for anyone wondering extract the optifine file then proceed to use the one labeled with _mod_g7
