### ISSUE TITLE
OptiForge-MC1.16.5-0.5.5 doesn´t work 

### ISSUE THREAD

**Issue by NaviEsket** [ZekerZhayard/OptiForge#79]
hey,

i need some help on the forge version: OptiForge-MC1.16.5-0.5.5.
It keeps crashing......

[2021-04-29-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398385/2021-04-29-1.log.gz)
[debug.log](https://github.com/ZekerZhayard/OptiForge/files/6398386/debug.log)
[debug-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398387/debug-1.log.gz)
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/6398388/latest.log)

![Screenshot 2021-04-29 140416](https://user-images.githubusercontent.com/81714255/116548378-67afe780-a8f4-11eb-8bac-f9e7ee5e5813.png)

Thanks,
your Leon

**Comment by NaviEsket** [comment]
And if someone says JUST update Optifine, i did........

Still crashes!


[2021-04-29-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398412/2021-04-29-1.log.gz)
[debug.log](https://github.com/ZekerZhayard/OptiForge/files/6398413/debug.log)
[debug-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398414/debug-1.log.gz)
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/6398415/latest.log)



![Optifine HD U G8 pre12](https://user-images.githubusercontent.com/81714255/116548582-bc536280-a8f4-11eb-9981-b00613a40a71.PNG)

**Comment by ZekerZhayard** [comment]
It's an issue between OptiFine itself and Chlorine, not related to OptiForge.

**Comment by NaviEsket** [comment]
Ah okay im gonna try putting it out.

**Comment by NaviEsket** [comment]
Nope it crashed.

**Comment by NaviEsket** [comment]
With both version of Optifine:
1) preview_OptiFine_1.16.5_HD_U_G8_pre12
and
2) OptiFine_1.16.5_HD_U_G7

**Comment by ZekerZhayard** [comment]
any new crash logs?

**Comment by NaviEsket** [comment]
[2021-04-29-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398457/2021-04-29-1.log.gz)
[debug.log](https://github.com/ZekerZhayard/OptiForge/files/6398458/debug.log)
[debug-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398459/debug-1.log.gz)
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/6398460/latest.log)

**Comment by NaviEsket** [comment]
Any ideas how to fix it?

**Comment by ZekerZhayard** [comment]
> [2021-04-29-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398457/2021-04-29-1.log.gz)
> [debug.log](https://github.com/ZekerZhayard/OptiForge/files/6398458/debug.log)
> [debug-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398459/debug-1.log.gz)
> [latest.log](https://github.com/ZekerZhayard/OptiForge/files/6398460/latest.log)

your behavior is called 「养蛊」 in a Chinese word, it means you are trying to put all same things to one place, but they are all conflict

**Comment by ZekerZhayard** [comment]
I have no word to describe the mods you installed anymore

**Comment by NaviEsket** [comment]
So im gonna try put EVERYTHING out and run then!

**Comment by ZekerZhayard** [comment]
Chlorine, mcmt, performant are all conflict with optifine

**Comment by NaviEsket** [comment]
And i did not work.

[2021-04-29-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398515/2021-04-29-1.log.gz)
[debug.log](https://github.com/ZekerZhayard/OptiForge/files/6398516/debug.log)
[debug-1.log.gz](https://github.com/ZekerZhayard/OptiForge/files/6398517/debug-1.log.gz)
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/6398518/latest.log)

**Comment by NaviEsket** [comment]
My mod folder!

![Screenshot 2021-04-29 143339](https://user-images.githubusercontent.com/81714255/116551278-0c7ff400-a8f8-11eb-8e56-37646de35576.png)

**Comment by ZekerZhayard** [comment]
more crash info is not compatible with 1.16.x

**Comment by NaviEsket** [comment]
Okay one sec i gonna remove it.

**Comment by NaviEsket** [comment]
OMG tf it did work..... HOW???

**Comment by ZekerZhayard** [comment]
If it did, then close this issue
