### ISSUE TITLE
optiforge doesent work with latest version of optifine

### ISSUE THREAD

**Issue by InnerCato** [ZekerZhayard/OptiForge#90]
when I tried to install optiforge and optifine (no I didn't put optifine in my mods folder) Minecraft turns on but the mod doesn't load. (Optifine version OptiFine_1.17.1_HD_U_G

Logs:
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/7201525/latest.log)

**Comment by ZekerZhayard** [comment]
can you provide logs?

**Comment by InnerCato** [comment]
ok
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/7201508/latest.log)

**Comment by ZekerZhayard** [comment]
Did not see any useful exceptions, Which mod you are using cannot be loaded?

**Comment by InnerCato** [comment]
optiforge

**Comment by ZekerZhayard** [comment]
How do you judge that it is not loaded?

**Comment by InnerCato** [comment]
it doesn't show in mods menu

**Comment by ZekerZhayard** [comment]
https://youtu.be/v78O0c9jie4?t=260 
Why do you think this is the only criterion, There are many forms of forge mod, what you see is only one of them

**Comment by InnerCato** [comment]
wait a sec i by mistake sent old logs

**Comment by ZekerZhayard** [comment]
I mean, optiforge 1.17.1 is not displayed in the mod menu originally

**Comment by InnerCato** [comment]
newer logs:
[latest.log](https://github.com/ZekerZhayard/OptiForge/files/7201561/latest.log)

**Comment by InnerCato** [comment]
optifine was loaded but i was Dumb
