### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by PistonUser** [ZekerZhayard/OptiForge#94]
Doesn't optifine already work with forge?

**Comment by vPubneutral** [comment]
Technically it does, but this mod usually comes out for a new version of Minecraft before OptiFine adds Forge support for that version themselves. For example, OptiFine didn't support Forge 1.17.1 natively until H1_pre2 released on 9/21, but OptiForge allowed OptiFine and Forge for 1.17.1 to work as early as 8/14.
