### ISSUE TITLE
1.17.1 game crashed whilst registering texture

### ISSUE THREAD

**Issue by KailySeitz** [ZekerZhayard/OptiForge#96]
Was able to run the game once with optifine and optiforge running after a restart of the game it will not launch anymore.

I've tried both the preview versions of Optifine for Minecraft 1.17.1

[crash-2021-10-25_22.46.38-client.txt](https://github.com/ZekerZhayard/OptiForge/files/7413488/crash-2021-10-25_22.46.38-client.txt)

**Comment by ZekerZhayard** [comment]
it should be fixed in OptiFine H1 pre8
